### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by monsoft** [bararchy/ruby-SSLscanner#11]
This is what I got when I tried to run sslscanner:

# ./sslscanner.rb 
./sslscanner.rb:282: odd number list for Hash
options = {debug: false, check_cert: false, port: 443}
                 ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '}'
options = {debug: false, check_cert: false, port: 443}
                 ^
./sslscanner.rb:282: Can't assign to false
options = {debug: false, check_cert: false, port: 443}
                        ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '='
options = {debug: false, check_cert: false, port: 443}
                                    ^
./sslscanner.rb:282: Can't assign to false
options = {debug: false, check_cert: false, port: 443}
                                           ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '='
options = {debug: false, check_cert: false, port: 443}

**Comment by bararchy** [comment]
hi @monsoft , I'm glad you are using the program :)

You are missing the needed arguments (I'll add an Usage error for this sort of thing.

The right way to use it is this:
./sslscanner.rb -s google.com -p 443 -c 

Where:
```-s``` = ip or hostname of the site\server you want to scan
```-p``` = the port you want to scan on that server
```-c``` = show certificate information

**Comment by monsoft** [comment]
Hi,

This doesn't work as well. I check it before I created this case:

# ./sslscanner.rb -s google.com -p 433 -c
./sslscanner.rb:282: odd number list for Hash
options = {debug: false, check_cert: false, port: 443}
                 ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '}'
options = {debug: false, check_cert: false, port: 443}
                 ^
./sslscanner.rb:282: Can't assign to false
options = {debug: false, check_cert: false, port: 443}
                        ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '='
options = {debug: false, check_cert: false, port: 443}
                                    ^
./sslscanner.rb:282: Can't assign to false
options = {debug: false, check_cert: false, port: 443}
                                           ^
./sslscanner.rb:282: syntax error, unexpected ':', expecting '='
options = {debug: false, check_cert: false, port: 443}
                                                 ^
Are any additional modules are required ?
I'm testing your program on freshly installed CentOS 6.7 and ruby version 1.8.7

**Comment by bararchy** [comment]
oh , that makes sense sorry .

Ruby > 2.0.0
colorize gem ( gem install colorize)

**Comment by bararchy** [comment]
@monsoft Just checking if the previous suggestion helped, is the program running as it should  ?

**Comment by bararchy** [comment]
@monsoft I'm closing this issue, feel free to comment on it if you are still getting this error.
