### ISSUE TITLE
Cache results until end of scan and format before printing

### ISSUE THREAD

**Issue by bararchy** [bararchy/ruby-SSLscanner#13]
@wolfedale , Now that multi-threading is working, maybe we should do something like that.

```ruby
@ssl2_array = []
@ssl3_array = []
@tls1_array = []
@tls1_1_array = []
@tls1_2_array = []

# Now instead of printing we should add the findigs to the right array

if protocol == ssl2
  @ssl2_array << data
end

# Then, we can print it in a nice order

puts @ssl2_array.join("\n")
puts @ssl3.... etc etc
```
What do you think ?

**Comment by wolfedale** [comment]
I agree :-) Sorted list looks much better, but since we are changing the whole structure I guess we can simply return it using Array or Hash and print in nice order and colours on one method :-) I will try to do it.

**Comment by wolfedale** [comment]
Added to scanHost.rb.
