### ISSUE TITLE
Installation instructions either incomplete or type-o

### ISSUE THREAD

**Issue by dfgilbert** [bararchy/ruby-SSLscanner#15]
this might be obvious to ruby people, but I am new

After following the instructions I get this error while running

`require': cannot load such file -- prawn (LoadError)

I have to install prawn, the instructions say 'pawn'

**Comment by bararchy** [comment]
@dfgilbert Good catch, sorry.

Fixed --> 6220f0b078a9919ed338d1be1e380fd0284df18f
