### ISSUE TITLE
undefined method `strip' for nil:NilClass during execution

### ISSUE THREAD

**Issue by dfgilbert** [bararchy/ruby-SSLscanner#16]
OSX 10.9.5
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

when executing 

./sslscanner.rb -s <SERVER> -p <PORT> -c

I get the following

undefined method `strip' for nil:NilClass
./sslscanner.rb:206:in `get_certificate_information'
./sslscanner.rb:64:in `ssl_scan'
./sslscanner.rb:331:in `block in <main>'
./sslscanner.rb:329:in `fork'
./sslscanner.rb:329:in `<main>'

**Comment by bararchy** [comment]
@dfgilbert Hi, 

Looking at your command, it seems you are missing the -s and -p values.
Where ```-s example.com and -p 443``` (for example)

**Comment by bararchy** [comment]
@dfgilbert I'm closing this issue, please comment if you want me to reopen it.
